#include<iostream.h>
#include<conio.h>
#include<graphics.h>

void background()
{
	textcolor(2);
	cprintf("   _.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-,");cout<<endl;
	cprintf(" ,'_.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.`.");  cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ) )                                                                       ( ( ");cout<<endl;
	cprintf(" ( (                                                                       ) )"); cout<<endl;
	cprintf(" ( (_.-._.-._.-._.-._.-._.-.-._.--._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.) )");cout<<endl;
	cprintf("  `._.-._.-._.-._.-._.-._.-._.-.-._.-.-._.-._.-._.-._.-._.-._.-._.-._.-._.-,' ");//cout<<endl;
	textcolor(7);
}
