#include<iostream.h>
#include<conio.h>
#include<iomanip.h>
#include<stdio.h>


void small_box()
{

	char x=5,z=32;
	gotoxy(19,8);
	cout<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z;
	gotoxy(19,9);
	cout<<x;
	gotoxy(19,10);
	cout<<x;
	gotoxy(19,11);
	cout<<x;
	gotoxy(19,12);
	cout<<x;
	gotoxy(19,13);
	cout<<x;
	gotoxy(19,14);
	cout<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z;
	gotoxy(61,9);
	cout<<x;
	gotoxy(61,10);
	cout<<x;
	gotoxy(61,11);
	cout<<x;
	gotoxy(61,12);
	cout<<x;
	gotoxy(61,13);
	cout<<x;
	gotoxy(61,14);
	cout<<x;
       /*	gotoxy(25,11);
	cout<<"Account Created Successfully...";
	getch();*/
}

void medium_box()
{

	char x=5,z=32;
	gotoxy(19,8);
	cout<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z;
	gotoxy(19,9);
	cout<<x;
	gotoxy(19,10);
	cout<<x;
	gotoxy(19,11);
	cout<<x;
	gotoxy(19,12);
	cout<<x;
	gotoxy(19,13);
	cout<<x;
	gotoxy(19,14);
	cout<<x;
	gotoxy(19,15);
	cout<<x;
	gotoxy(19,16);
	cout<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z;
	gotoxy(61,9);
	cout<<x;
	gotoxy(61,10);
	cout<<x;
	gotoxy(61,11);
	cout<<x;
	gotoxy(61,12);
	cout<<x;
	gotoxy(61,13);
	cout<<x;
	gotoxy(61,14);
	cout<<x;
	gotoxy(61,15);
	cout<<x;
	gotoxy(61,16);
	cout<<x;
       /*	gotoxy(25,11);
	cout<<"Account Created Successfully...";
	getch();*/
}

void operation_box()
{

	char x=5,z=32;
	gotoxy(21,5);
	cout<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z;
	gotoxy(21,6);
	cout<<x;
	gotoxy(21,7);
	cout<<x;
	gotoxy(21,8);
	cout<<x;
	gotoxy(21,9);
	cout<<x;
	gotoxy(21,10);
	cout<<x;
	gotoxy(21,11);
	cout<<x;
	gotoxy(21,12);
	cout<<x;
	gotoxy(21,13);
	cout<<x;
	gotoxy(21,14);
	cout<<x;
	gotoxy(21,15);
	cout<<x;
	gotoxy(21,16);
	cout<<x;
	gotoxy(21,17);
	cout<<x;
	gotoxy(21,18);
	cout<<x;
	gotoxy(21,19);
	cout<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z<<x<<z;
	gotoxy(59,6);
	cout<<x;
	gotoxy(59,7);
	cout<<x;
	gotoxy(59,8);
	cout<<x;
	gotoxy(59,9);
	cout<<x;
	gotoxy(59,10);
	cout<<x;
	gotoxy(59,11);
	cout<<x;
	gotoxy(59,12);
	cout<<x;
	gotoxy(59,13);
	cout<<x;
	gotoxy(59,14);
	cout<<x;
	gotoxy(59,15);
	cout<<x;
	gotoxy(59,16);
	cout<<x;
	gotoxy(59,17);
	cout<<x;
	gotoxy(59,18);
	cout<<x;
	gotoxy(59,19);
	cout<<x;
       /*	gotoxy(25,11);
	cout<<"Account Created Successfully...";
	getch();*/
}
